### ISSUE TITLE
Ejected A-143 missing Canopy/seat after repair.

### ISSUE THREAD

**Issue by SaltySeabiscuit** [Xeno69/Domination#129] opened 2020-04-03 23:33 UTC
A-143 Buzzard, if repaired after being ejected from is missing both the canopy and ejection seat. This also prevents the pilot from ejecting again in a repaired aircraft, although it is still flyable. Unsure if this also applies to any other jets at this time
![image](https://user-images.githubusercontent.com/24305770/78412571-b0bb3c80-760b-11ea-96e4-9d76727312e3.png)

**Comment by Xeno69** [comment] 2020-04-04 12:45
Well, the game itself locks planes without ejection seat and canopy for players.  Or in other words, a player should no longer be able to fly (of course one can unlock it).

In the A3 1.98 RC you are no longer able to start the engine again (though I can't say if it was already true for 1.96)

**Comment by SaltySeabiscuit** [comment] 2020-04-04 13:14
Sorry, allow me to clarify the bug here.
When "Wreck Repaired" at the Wreck Repair Point inside the mission, it doesn't have the canopy or ejection seat, but is unlocked for use.

**Comment by Xeno69** [comment] 2020-04-04 13:42
Well, I can not reproduce this (yet again).

Just tested it again now. The Buzzard spawns with a canopy and an ejection seat when a buzzard wreck gets put on the wreck repair point. And of course does this because createVehicle (which is used) creates completely new vehicle objects. The destroyed vehicle is deleted before the new one is created.

Closing.

**Closed by Xeno69** 2020-04-04 13:42 UTC

**Comment by SaltySeabiscuit** [comment] 2020-04-04 14:28
Just tried this again using an FA181 for sanity, Ejecting before crashing, then repairing the wreck once again didn't re spawn the canopy or seat. Some form of last vehicle state must be being stored and used for the wreck repair because it is re-spawning with the pylon loadout it was destroyed with.
